# -----------------------------------------------------------------------------
# Sync forked master
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.1 
# -----------------------------------------------------------------------------
name: sync-fork

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    steps:
       - name: foobar
         run: echo foobar
#      - name: Sync master
#        uses: tgymnich/fork-sync@v1.2.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          owner: MuseumofModernArt
#          base: master
#          head: master
#          merge_method: rebase

#      - name: Sync postgresql
#        uses: tgymnich/fork-sync@v1.2.1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          owner: MuseumofModernArt
#          base: master
#          head: postgresql
#          merge_method: rebase
