# -----------------------------------------------------------------------------
# Sync forked master
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.1.0 
# -----------------------------------------------------------------------------
name: sync-fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:       # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync master
        uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MuseumofModernArt
          base: master
          head: master
          merge_method: rebase

      - name: Sync postgresql
        uses: tgymnich/fork-sync@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: MuseumofModernArt
          base: master
          head: postgresql
          merge_method: rebase
